import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const PJS = Plus_Jakarta_Sans({ weight: ["500", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kanban",
  description: "Generated by NextJS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/logo-mobile.svg" />
      </head>
      <body className={PJS.className}>{children}</body>
    </html>
  );
}
